openapi: 3.0.0
info:
  title: Admin Service
  version: 0.0.0
tags: []
paths:
  /tenant-clients:
    get:
      operationId: TenantClients_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantClient'
  /tenant-clients/{id}:
    get:
      operationId: TenantClients_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/TenantClient'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantClient'
components:
  schemas:
    TenantClient:
      type: object
      required:
        - name
      properties:
        name:
          type: string
servers:
  - url: https://api.example.com
    variables: {}
